---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr?ref=eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09
- https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-k8s?ref=eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-proxy-dns?ref=eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr-proxy?ref=eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09
- https://github.com/networkservicemesh/deployments-k8s/apps/admission-webhook-k8s?ref=eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09

resources:
  - namespace.yaml

patchesStrategicMerge:
- patch-nsmgr-proxy.yaml
- patch-registry-proxy-dns.yaml
- patch-registry.yaml
