---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- ../../../../apps/nse-vl3-vpp
- ../../../../apps/vl3-ipam

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
