---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-kernel2ethernet2kernel-vfio2noop

resources:
  - ns-kernel2ethernet2kernel-vfio2noop.yaml
  - netsvc.yaml
  - ../../../apps/nse-kernel
  - ../../../apps/nsc-vfio
  - ../../../apps/nse-vfio
  - client.yaml

patchesStrategicMerge:
  - patch-nse.yaml
  - patch-nsc-vfio.yaml
  - patch-nse-vfio.yaml
