---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-webhook-smartvf

resources:
- ns-webhook.yaml
- postgres-cl.yaml
- netsvc.yaml
- ../../../apps/nse-kernel

patchesStrategicMerge:
- patch-nse.yaml
