---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-registry-local-endpoint

resources:
- ns-registry-local-endpoint.yaml
- ../base

patchesStrategicMerge:
- patch-nse.yaml
