---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-remote-nsm-system-restart-memif-ip

resources:
- ns-remote-nsm-system-restart-memif-ip.yaml
- netsvc.yaml
- ../../../apps/nsc-memif
- ../../../apps/nse-memif

patchesStrategicMerge:
- patch-nsc.yaml
- patch-nse.yaml
