---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

resources:
  - ../../../apps/forwarder-vpp

configMapGenerator:
  - name: device-selector
    files:
      - selector
patchesStrategicMerge:
  - patch-forwarder-vpp.yaml
