---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
  - https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09

configMapGenerator:
  - name: device-selector
    files:
      - selector
patchesStrategicMerge:
  - patch-forwarder-vpp.yaml
