---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-select-forwarder

resources:
- ns-select-forwarder.yaml
- client.yaml
- service.yaml
- forwarder.yaml
- ../../../apps/nse-kernel

patchesStrategicMerge:
- nse-patch.yaml
