---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-supplier-k8s?ref=27af934a97ce233926204569f84bd932d1d800b8

patchesStrategicMerge:
- patch-supplier.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap-server
    files:
      - pod-template.yaml
  - name: iptables-map
    files:
      - iptables-map.yaml

generatorOptions:
  disableNameSuffixHash: true
