---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-remote-nsmgr-restart

resources:
- ns-remote-nsmgr-restart.yaml
- netsvc.yaml
- client.yaml
- ../../../apps/nse-kernel

patchesStrategicMerge:
- patch-nse.yaml
