---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-4
  labels:
    app: alpine-4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine-4
  template:
    metadata:
      labels:
        app: alpine-4
      annotations:
        networkservicemesh.io: kernel://finance-bridge/nsm-1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - alpine-4
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: alpine
          image: alpine:3.15.0
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
