---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-memif2ip2memif-ipv6

resources:
- ns-memif2ip2memif-ipv6.yaml
- netsvc.yaml
- ../../../../apps/nsc-memif
- ../../../../apps/nse-memif

patchesStrategicMerge:
- patch-nsc.yaml
- patch-nse.yaml
