---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

resources:
  - nsm-system-namespace.yaml
  - ../../../apps/csi-driver
  - ../../../apps/nsmgr
  - ../../../apps/forwarder-vpp
  - ../../../apps/registry-k8s
  - ../../../apps/admission-webhook-k8s

patches:
  - path: patch-nsmgr.yaml
  - path: patch-forwarder-vpp.yaml
  - path: patch-registry-k8s.yaml
  - path: patch-admission-webhook-k8s.yaml
