---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-interdomain-dns

resources:
- namespace.yaml
- coredns-config-map.yaml
- ../../../../../apps/nse-kernel

patchesStrategicMerge:
- patch-nse.yaml
