---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-vfio
spec:
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: NSM_LABELS
              value: serviceDomain:worker.domain
            - name: NSM_SERVICE_NAMES
              value: "vfio2noop: { addr: 0a:55:44:33:22:11 }"
            - name: NSM_REGISTER_SERVICE
              value: "false"
