---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-kernel2kernel-vlan

resources:
- ns-kernel2kernel-vlan.yaml
- netsvc.yaml
- ../../../apps/nsc-kernel
- ../../../apps/nse-vlan-vpp

patchesStrategicMerge:
- patch-nsc.yaml
- patch-nse.yaml
