---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-memif2ethernet2memif

resources:
- ns-memif2ethernet2memif.yaml
- netsvc.yaml
- ../../../apps/nsc-memif
- ../../../apps/nse-memif

patchesStrategicMerge:
- patch-nsc.yaml
- patch-nse.yaml
