---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: nginx
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        # restricted k8s policy requires unprivileged containers
        image: nginxinc/nginx-unprivileged
        ports:
        - containerPort: 8080
      - name: nse
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        env:
          - name: NSM_SERVICE_NAMES
            value: "nginx"
          - name: NSM_REGISTER_SERVICE
            value: "false"
          - name: NSM_CIDR_PREFIX
            value: 172.16.1.100/31
      volumes:
        - name: spire-agent-socket
          hostPath: null
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
        - name: nsm-socket
          hostPath: null
          csi:
            driver: "csi.networkservicemesh.io"
            readOnly: true
