---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsc-vfio
spec:
  template:
    spec:
      containers:
        - name: nsc
          env:
            - name: NSM_NETWORK_SERVICES
              value: vfio://vfio2noop-vlantag?sriovToken=worker.domain/10G
