---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

bases:
- ../../../apps/nsc-kernel
- ../../../apps/nse-vl3-vpp
- ../../../apps/vl3-ipam

resources:
- ../../../examples/features/vl3-basic/vl3-netsvc.yaml

patchesStrategicMerge:
- ../../../examples/features/vl3-basic/nsc-patch.yaml
- ../../../examples/features/vl3-basic/nse-patch.yaml
