---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

resources:
- nsm-system-namespace.yaml
- ../../apps/nsmgr
- ../../apps/forwarder-ovs
- ../../apps/registry-k8s
- ../../apps/admission-webhook-k8s
