---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-sriov-kernel2noop

resources:
- ../../../apps/nsc-kernel
- ../../../apps/nse-kernel
- namespace
- netsvc.yaml

patchesStrategicMerge:
- patch-nsc.yaml
- patch-nse.yaml
