---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-jaeger-and-prometheus

resources:
- ns-jaeger-and-prometheus.yaml
- client.yaml
- netsvc.yaml
- ../../../../apps/nse-kernel

patchesStrategicMerge:
- patch-nse.yaml
