---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../apps/nse-supplier-k8s

patchesStrategicMerge:
- patch-supplier.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - pod-template.yaml

generatorOptions:
  disableNameSuffixHash: true
