---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-kernel2vlan-multins-1

resources:
  - first-client.yaml
  - netsvc.yaml
  - ../../../../apps/nse-remote-vlan

patchesStrategicMerge:
  - patch-nse.yaml
