---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09/examples/features/vl3-dns/nsc.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09/examples/features/vl3-dns/namespace.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/eb5c014d0ef4d67413babb2c1ce1c7f2acdf4f09/examples/features/vl3-dns/nse-patch.yaml
