---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- ../../../apps/nse-vl3-vpp
- ../../../apps/vl3-ipam

resources:
- ../../../examples/features/vl3-dns/nsc.yaml
- ../../../examples/features/vl3-dns/namespace.yaml
- ../../../examples/features/vl3-dns/vl3-netsvc.yaml

patchesStrategicMerge:
- ../../../examples/features/vl3-dns/nse-patch.yaml
