---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3-lb

resources:
- ns-vl3-lb.yaml
- netsvc.yaml
- finance-client.yaml
- finance-server.yaml
- ../../../apps/nse-vl3-vpp
- ../../../apps/vl3-ipam
- ../../../apps/vl3-lb

patchesStrategicMerge:
- nse-patch.yaml
- finance-lb-patch.yaml
