---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vfio2noop-vlantag

resources:
  - ns-vfio2noop-vlantag.yaml
  - ../../../apps/nsc-vfio
  - ../../../apps/nse-vfio
  - netsvc.yaml

patchesStrategicMerge:
  - patch-nsc-vfio.yaml
  - patch-nse-vfio.yaml
