---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-vfio
spec:
  template:
    spec:
      containers:
        - name: ponger
          command: ["/bin/bash", "/root/scripts/pong.sh", "ens6f3", "31", "0a:55:44:33:22:11", "1044"]
        - name: nse
          env:
            - name: NSM_LABELS
              value: serviceDomain:worker.domain
            - name: NSM_SERVICE_NAMES
              value: "vfio2noop-vlantag: { addr: 0a:55:44:33:22:11; vlan: 1044 }"
            - name: NSM_REGISTER_SERVICE
              value: "false"
