---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

bases:
- ../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: spire-server
  namespace: spire
  files:
  - server.conf
- name: spire-agent
  namespace: spire
  files:
  - agent.conf
- name: k8s-workload-registrar
  namespace: spire
  files:
    - k8s-workload-registrar.conf
