---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-vl3

resources:
- ../../../examples/features/vl3-scale-from-zero/autoscale-netsvc.yaml
- ../../../examples/features/vl3-scale-from-zero/vl3-netsvc.yaml

bases:
- ../../../apps/nsc-kernel
- ../../../apps/vl3-ipam
- ../../../apps/nse-supplier-k8s

patchesStrategicMerge:
- nsc-patch.yaml
- supplier-patch.yaml

configMapGenerator:
  - name: supplier-pod-template-configmap
    files:
      - ../../../examples/features/vl3-scale-from-zero/pod-template.yaml
