---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-spire-server-agent-restart

resources:
- netsvc.yaml
- client.yaml
- ../../../apps/nse-kernel

patchesStrategicMerge:
- patch-nse.yaml
